name: Export to designer xml
on:
  workflow_call:
    inputs:
      edt_version:
        type: string
        required: true
      
      artifact_name:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install EDT
      uses: IT-Medved/onec-setup-build-env-action@develop
      with:
        type: edt
        edt_version: ${{ inputs.edt_version }}
        cache: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10
        
    - name: convert configuration src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: fixtures/demo-configuration
        to: export/configuration
        timeout: 5
      timeout-minutes: 10
      
    - name: convert yaxunit src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: exts/yaxunit
        to: export/yaxunit
        timeout: 5
      timeout-minutes: 10
      
    - name: convert tests src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: tests
        to: export/tests
        timeout: 5
      timeout-minutes: 10
    
    - run: |
        cd export
        7za a -t7z ../export.7z ./

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: export.7z
        if-no-files-found: error
        retention-days: 1
